// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_main_cabi<T: Guest>(
    arg0: i32,
    arg1: i32,
    arg2: i32,
    arg3: i32,
    arg4: i32,
    arg5: i32,
    arg6: i32,
    arg7: i32,
    arg8: i32,
    arg9: i32,
    arg10: i32,
    arg11: i32,
    arg12: i32,
    arg13: i32,
    arg14: i32,
    arg15: i32,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::main(
        arg0 as u32,
        arg1 as u32,
        arg2 as u32,
        arg3 as u32,
        arg4 as u32,
        arg5 as u32,
        arg6 as u32,
        arg7 as u32,
        arg8 as u32,
        arg9 as u32,
        arg10 as u32,
        arg11 as u32,
        arg12 as u32,
        arg13 as u32,
        arg14 as u32,
        arg15 as u32,
    );
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let (t2_0, t2_1) = result0;
    *ptr1.add(0).cast::<i32>() = _rt::as_i32(t2_0);
    *ptr1.add(4).cast::<i32>() = _rt::as_i32(t2_1);
    ptr1
}
pub trait Guest {
    fn main(
        a1: u32,
        a2: u32,
        a3: u32,
        a4: u32,
        a5: u32,
        a6: u32,
        a7: u32,
        a8: u32,
        a9: u32,
        a10: u32,
        a11: u32,
        a12: u32,
        a13: u32,
        a14: u32,
        a15: u32,
        a16: u32,
    ) -> (u32, u32);
}
#[doc(hidden)]
macro_rules! __export_world_my_world_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "main")] unsafe extern "C" fn
        export_main(arg0 : i32, arg1 : i32, arg2 : i32, arg3 : i32, arg4 : i32, arg5 :
        i32, arg6 : i32, arg7 : i32, arg8 : i32, arg9 : i32, arg10 : i32, arg11 : i32,
        arg12 : i32, arg13 : i32, arg14 : i32, arg15 : i32,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_main_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4,
        arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_my_world_cabi;
#[repr(align(4))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 8]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 8]);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod component {
    pub mod test_package {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod env {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            pub fn compute(
                a1: u32,
                a2: u32,
                a3: u32,
                a4: u32,
                a5: u32,
                a6: u32,
                a7: u32,
                a8: u32,
                a9: u32,
                a10: u32,
                a11: u32,
                a12: u32,
                a13: u32,
                a14: u32,
                a15: u32,
                a16: u32,
            ) -> (u32, u32) {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "component:test-package/env")]
                    unsafe extern "C" {
                        #[link_name = "compute"]
                        fn wit_import1(
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import1(
                            _rt::as_i32(&a1),
                            _rt::as_i32(&a2),
                            _rt::as_i32(&a3),
                            _rt::as_i32(&a4),
                            _rt::as_i32(&a5),
                            _rt::as_i32(&a6),
                            _rt::as_i32(&a7),
                            _rt::as_i32(&a8),
                            _rt::as_i32(&a9),
                            _rt::as_i32(&a10),
                            _rt::as_i32(&a11),
                            _rt::as_i32(&a12),
                            _rt::as_i32(&a13),
                            _rt::as_i32(&a14),
                            _rt::as_i32(&a15),
                            _rt::as_i32(&a16),
                            ptr0,
                        )
                    };
                    let l2 = *ptr0.add(0).cast::<i32>();
                    let l3 = *ptr0.add(4).cast::<i32>();
                    let result4 = (l2 as u32, l3 as u32);
                    result4
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_my_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_my_world_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_my_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:test-package:my-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 386] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x83\x02\x01A\x02\x01\
A\x05\x01B\x03\x01o\x02yy\x01@\x10\x02a1y\x02a2y\x02a3y\x02a4y\x02a5y\x02a6y\x02\
a7y\x02a8y\x02a9y\x03a10y\x03a11y\x03a12y\x03a13y\x03a14y\x03a15y\x03a16y\0\0\x04\
\0\x07compute\x01\x01\x03\0\x1acomponent:test-package/env\x05\0\x01o\x02yy\x01@\x10\
\x02a1y\x02a2y\x02a3y\x02a4y\x02a5y\x02a6y\x02a7y\x02a8y\x02a9y\x03a10y\x03a11y\x03\
a12y\x03a13y\x03a14y\x03a15y\x03a16y\0\x01\x04\0\x04main\x01\x02\x04\0\x1fcompon\
ent:test-package/my-world\x04\0\x0b\x0e\x01\0\x08my-world\x03\0\0\0G\x09producer\
s\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.4\
1.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
