[package]
name = "r3-baseline"
version.workspace = true
authors.workspace = true
edition = "2024"

[[bin]]
name = "r3-instrument"
path = "src/bin/instrument.rs"

[[bin]]
name = "r3-instrument-component"
path = "src/bin/instrument_component.rs"

[[bin]]
name = "r3-record"
path = "src/bin/record.rs"

[[bin]]
name = "r3-record-component"
path = "src/bin/record_component.rs"

[dependencies]
wirm.workspace = true
wat.workspace = true
anyhow.workspace = true
clap.workspace = true
log.workspace = true
env_logger.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
postcard = { version = "1", features = ["use-std"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt", "macros"] }
