[package]
name = "crimp-glue-driver"
edition = "2024"
version.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
wasm-crimp.workspace = true
anyhow.workspace = true
env_logger.workspace = true
clap.workspace = true
log.workspace = true
hex = "0.4.3"

[features]
default = ["glue"]
multi-component = []
# When disabled, this feature allows building the driver without glue imports (useful for testing)
glue = []

[target.'cfg(target_arch = "wasm32")']
rustflags = ["-C", "link-arg=--export-memory",]
