// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_main_cabi<T: Guest>(arg0: *mut u8) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let l0 = *arg0.add(0).cast::<i32>();
    let l1 = *arg0.add(4).cast::<i32>();
    let l2 = *arg0.add(8).cast::<i32>();
    let l3 = *arg0.add(12).cast::<i32>();
    let l4 = *arg0.add(16).cast::<i32>();
    let l5 = *arg0.add(20).cast::<i32>();
    let l6 = *arg0.add(24).cast::<i32>();
    let l7 = *arg0.add(28).cast::<i32>();
    let l8 = *arg0.add(32).cast::<i32>();
    let l9 = *arg0.add(36).cast::<i32>();
    let l10 = *arg0.add(40).cast::<i32>();
    let l11 = *arg0.add(44).cast::<i32>();
    let l12 = *arg0.add(48).cast::<i32>();
    let l13 = *arg0.add(52).cast::<i32>();
    let l14 = *arg0.add(56).cast::<i32>();
    let l15 = *arg0.add(60).cast::<i32>();
    let l16 = *arg0.add(64).cast::<i32>();
    let result17 = T::main(
        l0 as u32,
        l1 as u32,
        l2 as u32,
        l3 as u32,
        l4 as u32,
        l5 as u32,
        l6 as u32,
        l7 as u32,
        l8 as u32,
        l9 as u32,
        l10 as u32,
        l11 as u32,
        l12 as u32,
        l13 as u32,
        l14 as u32,
        l15 as u32,
        l16 as u32,
    );
    _rt::cabi_dealloc(arg0, 68, 4);
    let ptr18 = (&raw mut _RET_AREA.0).cast::<u8>();
    let (t19_0, t19_1) = result17;
    *ptr18.add(0).cast::<i32>() = _rt::as_i32(t19_0);
    *ptr18.add(4).cast::<i32>() = _rt::as_i32(t19_1);
    ptr18
}
pub trait Guest {
    fn main(
        a1: u32,
        a2: u32,
        a3: u32,
        a4: u32,
        a5: u32,
        a6: u32,
        a7: u32,
        a8: u32,
        a9: u32,
        a10: u32,
        a11: u32,
        a12: u32,
        a13: u32,
        a14: u32,
        a15: u32,
        a16: u32,
        a17: u32,
    ) -> (u32, u32);
}
#[doc(hidden)]
macro_rules! __export_world_my_world_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "main")] unsafe extern "C" fn
        export_main(arg0 : * mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_main_cabi::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_my_world_cabi;
#[repr(align(4))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 8]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 8]);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod component {
    pub mod test_package {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod env {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            pub fn compute(
                a1: u32,
                a2: u32,
                a3: u32,
                a4: u32,
                a5: u32,
                a6: u32,
                a7: u32,
                a8: u32,
                a9: u32,
                a10: u32,
                a11: u32,
                a12: u32,
                a13: u32,
                a14: u32,
                a15: u32,
                a16: u32,
                a17: u32,
            ) -> (u32, u32) {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 68]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 68]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    *ptr0.add(0).cast::<i32>() = _rt::as_i32(&a1);
                    *ptr0.add(4).cast::<i32>() = _rt::as_i32(&a2);
                    *ptr0.add(8).cast::<i32>() = _rt::as_i32(&a3);
                    *ptr0.add(12).cast::<i32>() = _rt::as_i32(&a4);
                    *ptr0.add(16).cast::<i32>() = _rt::as_i32(&a5);
                    *ptr0.add(20).cast::<i32>() = _rt::as_i32(&a6);
                    *ptr0.add(24).cast::<i32>() = _rt::as_i32(&a7);
                    *ptr0.add(28).cast::<i32>() = _rt::as_i32(&a8);
                    *ptr0.add(32).cast::<i32>() = _rt::as_i32(&a9);
                    *ptr0.add(36).cast::<i32>() = _rt::as_i32(&a10);
                    *ptr0.add(40).cast::<i32>() = _rt::as_i32(&a11);
                    *ptr0.add(44).cast::<i32>() = _rt::as_i32(&a12);
                    *ptr0.add(48).cast::<i32>() = _rt::as_i32(&a13);
                    *ptr0.add(52).cast::<i32>() = _rt::as_i32(&a14);
                    *ptr0.add(56).cast::<i32>() = _rt::as_i32(&a15);
                    *ptr0.add(60).cast::<i32>() = _rt::as_i32(&a16);
                    *ptr0.add(64).cast::<i32>() = _rt::as_i32(&a17);
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "component:test-package/env")]
                    unsafe extern "C" {
                        #[link_name = "compute"]
                        fn wit_import2(_: *mut u8, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0, ptr1) };
                    let l3 = *ptr1.add(0).cast::<i32>();
                    let l4 = *ptr1.add(4).cast::<i32>();
                    let result5 = (l3 as u32, l4 as u32);
                    result5
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_my_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_my_world_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_my_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:component:test-package:my-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 396] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8d\x02\x01A\x02\x01\
A\x05\x01B\x03\x01o\x02yy\x01@\x11\x02a1y\x02a2y\x02a3y\x02a4y\x02a5y\x02a6y\x02\
a7y\x02a8y\x02a9y\x03a10y\x03a11y\x03a12y\x03a13y\x03a14y\x03a15y\x03a16y\x03a17\
y\0\0\x04\0\x07compute\x01\x01\x03\0\x1acomponent:test-package/env\x05\0\x01o\x02\
yy\x01@\x11\x02a1y\x02a2y\x02a3y\x02a4y\x02a5y\x02a6y\x02a7y\x02a8y\x02a9y\x03a1\
0y\x03a11y\x03a12y\x03a13y\x03a14y\x03a15y\x03a16y\x03a17y\0\x01\x04\0\x04main\x01\
\x02\x04\0\x1fcomponent:test-package/my-world\x04\0\x0b\x0e\x01\0\x08my-world\x03\
\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-\
bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
